set autocommit off;
drop table Pima PURGE;
drop table Maricopa PURGE;
drop table Mohave PURGE;
drop table Pinal PURGE;
drop table Yavapai PURGE;
drop table Apache PURGE;
drop table Cochise PURGE;
drop table Yuma PURGE;
drop table LaPaz PURGE;
drop table Greenlee PURGE;
drop table Graham PURGE;
drop table Navajo PURGE;
drop table Coconino PURGE;
drop table Gila PURGE;
drop table SantaCruz PURGE;

create table Pima (
	FiscalYear				integer,
	St						varchar(200),
	County					varchar(200),
	LEAEntityID         	integer,
	LEACTDSNumber			integer,
	LEAName					varchar(200),
	SchoolEntityID    		integer,
	SchoolCTDSNumber		integer,
	SchoolName				varchar(200),
	CharterSchool			varchar(200),
	MathMeanScaleScore		integer,
	MathFallsFarBelowPer	integer,
	MathApproachesPer		integer,
	MathMeetsPer			integer,
	MathExceedsPer			integer,
	MathPassingPer			integer,
	ReaMeanScaleScore		integer,
	ReaFallsFarBelowPer		integer,
	ReaApproachesPer		integer,
	ReaMeetsPer				integer,
	ReaExceedsPer			integer,
	ReaPassingPer			integer,
	WriMeanScaleScore		integer,
	WriFallsFarBelowPer		integer,
	WriApproachesPer		integer,
	WriMeetsPer				integer,
	WriExceedsPer			integer,
	WriPassingPer			integer,
	SciMeanScaleScorePer	integer,
	SciFallsFarBelowPer		integer,
	SciApproachesPer		integer,
	SciMeetsPer				integer,
	SciExceedsPer			integer,
	SciPassingintegerPer 	integer,
    primary key (SchoolEntityID)
);

create table Maricopa (
	FiscalYear				integer,
	St						varchar(200),
	County					varchar(200),
	LEAEntityID         	integer,
	LEACTDSNumber			integer,
	LEAName					varchar(200),
	SchoolEntityID    		integer,
	SchoolCTDSNumber		integer,
	SchoolName				varchar(200),
	CharterSchool			varchar(200),
	MathMeanScaleScore		integer,
	MathFallsFarBelowPer	integer,
	MathApproachesPer		integer,
	MathMeetsPer			integer,
	MathExceedsPer			integer,
	MathPassingPer			integer,
	ReaMeanScaleScore		integer,
	ReaFallsFarBelowPer		integer,
	ReaApproachesPer		integer,
	ReaMeetsPer				integer,
	ReaExceedsPer			integer,
	ReaPassingPer			integer,
	WriMeanScaleScore		integer,
	WriFallsFarBelowPer		integer,
	WriApproachesPer		integer,
	WriMeetsPer				integer,
	WriExceedsPer			integer,
	WriPassingPer			integer,
	SciMeanScaleScorePer	integer,
	SciFallsFarBelowPer		integer,
	SciApproachesPer		integer,
	SciMeetsPer				integer,
	SciExceedsPer			integer,
	SciPassingintegerPer 	integer,
    primary key (SchoolEntityID)
);
create table Mohave (
	FiscalYear				integer,
	St						varchar(200),
	County					varchar(200),
	LEAEntityID         	integer,
	LEACTDSNumber			integer,
	LEAName					varchar(200),
	SchoolEntityID    		integer,
	SchoolCTDSNumber		integer,
	SchoolName				varchar(200),
	CharterSchool			varchar(200),
	MathMeanScaleScore		integer,
	MathFallsFarBelowPer	integer,
	MathApproachesPer		integer,
	MathMeetsPer			integer,
	MathExceedsPer			integer,
	MathPassingPer			integer,
	ReaMeanScaleScore		integer,
	ReaFallsFarBelowPer		integer,
	ReaApproachesPer		integer,
	ReaMeetsPer				integer,
	ReaExceedsPer			integer,
	ReaPassingPer			integer,
	WriMeanScaleScore		integer,
	WriFallsFarBelowPer		integer,
	WriApproachesPer		integer,
	WriMeetsPer				integer,
	WriExceedsPer			integer,
	WriPassingPer			integer,
	SciMeanScaleScorePer	integer,
	SciFallsFarBelowPer		integer,
	SciApproachesPer		integer,
	SciMeetsPer				integer,
	SciExceedsPer			integer,
	SciPassingintegerPer 	integer,
    primary key (SchoolEntityID)
);
create table Pinal (
	FiscalYear				integer,
	St						varchar(200),
	County					varchar(200),
	LEAEntityID         	integer,
	LEACTDSNumber			integer,
	LEAName					varchar(200),
	SchoolEntityID    		integer,
	SchoolCTDSNumber		integer,
	SchoolName				varchar(200),
	CharterSchool			varchar(200),
	MathMeanScaleScore		integer,
	MathFallsFarBelowPer	integer,
	MathApproachesPer		integer,
	MathMeetsPer			integer,
	MathExceedsPer			integer,
	MathPassingPer			integer,
	ReaMeanScaleScore		integer,
	ReaFallsFarBelowPer		integer,
	ReaApproachesPer		integer,
	ReaMeetsPer				integer,
	ReaExceedsPer			integer,
	ReaPassingPer			integer,
	WriMeanScaleScore		integer,
	WriFallsFarBelowPer		integer,
	WriApproachesPer		integer,
	WriMeetsPer				integer,
	WriExceedsPer			integer,
	WriPassingPer			integer,
	SciMeanScaleScorePer	integer,
	SciFallsFarBelowPer		integer,
	SciApproachesPer		integer,
	SciMeetsPer				integer,
	SciExceedsPer			integer,
	SciPassingintegerPer 	integer,
    primary key (SchoolEntityID)
);
create table Yavapai (
	FiscalYear				integer,
	St						varchar(200),
	County					varchar(200),
	LEAEntityID         	integer,
	LEACTDSNumber			integer,
	LEAName					varchar(200),
	SchoolEntityID    		integer,
	SchoolCTDSNumber		integer,
	SchoolName				varchar(200),
	CharterSchool			varchar(200),
	MathMeanScaleScore		integer,
	MathFallsFarBelowPer	integer,
	MathApproachesPer		integer,
	MathMeetsPer			integer,
	MathExceedsPer			integer,
	MathPassingPer			integer,
	ReaMeanScaleScore		integer,
	ReaFallsFarBelowPer		integer,
	ReaApproachesPer		integer,
	ReaMeetsPer				integer,
	ReaExceedsPer			integer,
	ReaPassingPer			integer,
	WriMeanScaleScore		integer,
	WriFallsFarBelowPer		integer,
	WriApproachesPer		integer,
	WriMeetsPer				integer,
	WriExceedsPer			integer,
	WriPassingPer			integer,
	SciMeanScaleScorePer	integer,
	SciFallsFarBelowPer		integer,
	SciApproachesPer		integer,
	SciMeetsPer				integer,
	SciExceedsPer			integer,
	SciPassingintegerPer 	integer,
    primary key (SchoolEntityID)
);
create table Apache (
	FiscalYear				integer,
	St						varchar(200),
	County					varchar(200),
	LEAEntityID         	integer,
	LEACTDSNumber			integer,
	LEAName					varchar(200),
	SchoolEntityID    		integer,
	SchoolCTDSNumber		integer,
	SchoolName				varchar(200),
	CharterSchool			varchar(200),
	MathMeanScaleScore		integer,
	MathFallsFarBelowPer	integer,
	MathApproachesPer		integer,
	MathMeetsPer			integer,
	MathExceedsPer			integer,
	MathPassingPer			integer,
	ReaMeanScaleScore		integer,
	ReaFallsFarBelowPer		integer,
	ReaApproachesPer		integer,
	ReaMeetsPer				integer,
	ReaExceedsPer			integer,
	ReaPassingPer			integer,
	WriMeanScaleScore		integer,
	WriFallsFarBelowPer		integer,
	WriApproachesPer		integer,
	WriMeetsPer				integer,
	WriExceedsPer			integer,
	WriPassingPer			integer,
	SciMeanScaleScorePer	integer,
	SciFallsFarBelowPer		integer,
	SciApproachesPer		integer,
	SciMeetsPer				integer,
	SciExceedsPer			integer,
	SciPassingintegerPer 	integer,
    primary key (SchoolEntityID)
);
create table Cochise (
	FiscalYear				integer,
	St						varchar(200),
	County					varchar(200),
	LEAEntityID         	integer,
	LEACTDSNumber			integer,
	LEAName					varchar(200),
	SchoolEntityID    		integer,
	SchoolCTDSNumber		integer,
	SchoolName				varchar(200),
	CharterSchool			varchar(200),
	MathMeanScaleScore		integer,
	MathFallsFarBelowPer	integer,
	MathApproachesPer		integer,
	MathMeetsPer			integer,
	MathExceedsPer			integer,
	MathPassingPer			integer,
	ReaMeanScaleScore		integer,
	ReaFallsFarBelowPer		integer,
	ReaApproachesPer		integer,
	ReaMeetsPer				integer,
	ReaExceedsPer			integer,
	ReaPassingPer			integer,
	WriMeanScaleScore		integer,
	WriFallsFarBelowPer		integer,
	WriApproachesPer		integer,
	WriMeetsPer				integer,
	WriExceedsPer			integer,
	WriPassingPer			integer,
	SciMeanScaleScorePer	integer,
	SciFallsFarBelowPer		integer,
	SciApproachesPer		integer,
	SciMeetsPer				integer,
	SciExceedsPer			integer,
	SciPassingintegerPer 	integer,
    primary key (SchoolEntityID)
);
create table Yuma (
	FiscalYear				integer,
	St						varchar(200),
	County					varchar(200),
	LEAEntityID         	integer,
	LEACTDSNumber			integer,
	LEAName					varchar(200),
	SchoolEntityID    		integer,
	SchoolCTDSNumber		integer,
	SchoolName				varchar(200),
	CharterSchool			varchar(200),
	MathMeanScaleScore		integer,
	MathFallsFarBelowPer	integer,
	MathApproachesPer		integer,
	MathMeetsPer			integer,
	MathExceedsPer			integer,
	MathPassingPer			integer,
	ReaMeanScaleScore		integer,
	ReaFallsFarBelowPer		integer,
	ReaApproachesPer		integer,
	ReaMeetsPer				integer,
	ReaExceedsPer			integer,
	ReaPassingPer			integer,
	WriMeanScaleScore		integer,
	WriFallsFarBelowPer		integer,
	WriApproachesPer		integer,
	WriMeetsPer				integer,
	WriExceedsPer			integer,
	WriPassingPer			integer,
	SciMeanScaleScorePer	integer,
	SciFallsFarBelowPer		integer,
	SciApproachesPer		integer,
	SciMeetsPer				integer,
	SciExceedsPer			integer,
	SciPassingintegerPer 	integer,
    primary key (SchoolEntityID)
);
create table LaPaz (
	FiscalYear				integer,
	St						varchar(200),
	County					varchar(200),
	LEAEntityID         	integer,
	LEACTDSNumber			integer,
	LEAName					varchar(200),
	SchoolEntityID    		integer,
	SchoolCTDSNumber		integer,
	SchoolName				varchar(200),
	CharterSchool			varchar(200),
	MathMeanScaleScore		integer,
	MathFallsFarBelowPer	integer,
	MathApproachesPer		integer,
	MathMeetsPer			integer,
	MathExceedsPer			integer,
	MathPassingPer			integer,
	ReaMeanScaleScore		integer,
	ReaFallsFarBelowPer		integer,
	ReaApproachesPer		integer,
	ReaMeetsPer				integer,
	ReaExceedsPer			integer,
	ReaPassingPer			integer,
	WriMeanScaleScore		integer,
	WriFallsFarBelowPer		integer,
	WriApproachesPer		integer,
	WriMeetsPer				integer,
	WriExceedsPer			integer,
	WriPassingPer			integer,
	SciMeanScaleScorePer	integer,
	SciFallsFarBelowPer		integer,
	SciApproachesPer		integer,
	SciMeetsPer				integer,
	SciExceedsPer			integer,
	SciPassingintegerPer 	integer,
    primary key (SchoolEntityID)
);
create table Graham (
	FiscalYear				integer,
	St						varchar(200),
	County					varchar(200),
	LEAEntityID         	integer,
	LEACTDSNumber			integer,
	LEAName					varchar(200),
	SchoolEntityID    		integer,
	SchoolCTDSNumber		integer,
	SchoolName				varchar(200),
	CharterSchool			varchar(200),
	MathMeanScaleScore		integer,
	MathFallsFarBelowPer	integer,
	MathApproachesPer		integer,
	MathMeetsPer			integer,
	MathExceedsPer			integer,
	MathPassingPer			integer,
	ReaMeanScaleScore		integer,
	ReaFallsFarBelowPer		integer,
	ReaApproachesPer		integer,
	ReaMeetsPer				integer,
	ReaExceedsPer			integer,
	ReaPassingPer			integer,
	WriMeanScaleScore		integer,
	WriFallsFarBelowPer		integer,
	WriApproachesPer		integer,
	WriMeetsPer				integer,
	WriExceedsPer			integer,
	WriPassingPer			integer,
	SciMeanScaleScorePer	integer,
	SciFallsFarBelowPer		integer,
	SciApproachesPer		integer,
	SciMeetsPer				integer,
	SciExceedsPer			integer,
	SciPassingintegerPer 	integer,
    primary key (SchoolEntityID)
);
create table Greenlee (
	FiscalYear				integer,
	St						varchar(200),
	County					varchar(200),
	LEAEntityID         	integer,
	LEACTDSNumber			integer,
	LEAName					varchar(200),
	SchoolEntityID    		integer,
	SchoolCTDSNumber		integer,
	SchoolName				varchar(200),
	CharterSchool			varchar(200),
	MathMeanScaleScore		integer,
	MathFallsFarBelowPer	integer,
	MathApproachesPer		integer,
	MathMeetsPer			integer,
	MathExceedsPer			integer,
	MathPassingPer			integer,
	ReaMeanScaleScore		integer,
	ReaFallsFarBelowPer		integer,
	ReaApproachesPer		integer,
	ReaMeetsPer				integer,
	ReaExceedsPer			integer,
	ReaPassingPer			integer,
	WriMeanScaleScore		integer,
	WriFallsFarBelowPer		integer,
	WriApproachesPer		integer,
	WriMeetsPer				integer,
	WriExceedsPer			integer,
	WriPassingPer			integer,
	SciMeanScaleScorePer	integer,
	SciFallsFarBelowPer		integer,
	SciApproachesPer		integer,
	SciMeetsPer				integer,
	SciExceedsPer			integer,
	SciPassingintegerPer 	integer,
    primary key (SchoolEntityID)
);
create table Navajo (
	FiscalYear				integer,
	St						varchar(200),
	County					varchar(200),
	LEAEntityID         	integer,
	LEACTDSNumber			integer,
	LEAName					varchar(200),
	SchoolEntityID    		integer,
	SchoolCTDSNumber		integer,
	SchoolName				varchar(200),
	CharterSchool			varchar(200),
	MathMeanScaleScore		integer,
	MathFallsFarBelowPer	integer,
	MathApproachesPer		integer,
	MathMeetsPer			integer,
	MathExceedsPer			integer,
	MathPassingPer			integer,
	ReaMeanScaleScore		integer,
	ReaFallsFarBelowPer		integer,
	ReaApproachesPer		integer,
	ReaMeetsPer				integer,
	ReaExceedsPer			integer,
	ReaPassingPer			integer,
	WriMeanScaleScore		integer,
	WriFallsFarBelowPer		integer,
	WriApproachesPer		integer,
	WriMeetsPer				integer,
	WriExceedsPer			integer,
	WriPassingPer			integer,
	SciMeanScaleScorePer	integer,
	SciFallsFarBelowPer		integer,
	SciApproachesPer		integer,
	SciMeetsPer				integer,
	SciExceedsPer			integer,
	SciPassingintegerPer 	integer,
    primary key (SchoolEntityID)
);
create table Coconino (
	FiscalYear				integer,
	St						varchar(200),
	County					varchar(200),
	LEAEntityID         	integer,
	LEACTDSNumber			integer,
	LEAName					varchar(200),
	SchoolEntityID    		integer,
	SchoolCTDSNumber		integer,
	SchoolName				varchar(200),
	CharterSchool			varchar(200),
	MathMeanScaleScore		integer,
	MathFallsFarBelowPer	integer,
	MathApproachesPer		integer,
	MathMeetsPer			integer,
	MathExceedsPer			integer,
	MathPassingPer			integer,
	ReaMeanScaleScore		integer,
	ReaFallsFarBelowPer		integer,
	ReaApproachesPer		integer,
	ReaMeetsPer				integer,
	ReaExceedsPer			integer,
	ReaPassingPer			integer,
	WriMeanScaleScore		integer,
	WriFallsFarBelowPer		integer,
	WriApproachesPer		integer,
	WriMeetsPer				integer,
	WriExceedsPer			integer,
	WriPassingPer			integer,
	SciMeanScaleScorePer	integer,
	SciFallsFarBelowPer		integer,
	SciApproachesPer		integer,
	SciMeetsPer				integer,
	SciExceedsPer			integer,
	SciPassingintegerPer 	integer,
    primary key (SchoolEntityID)
);
create table Gila (
	FiscalYear				integer,
	St						varchar(200),
	County					varchar(200),
	LEAEntityID         	integer,
	LEACTDSNumber			integer,
	LEAName					varchar(200),
	SchoolEntityID    		integer,
	SchoolCTDSNumber		integer,
	SchoolName				varchar(200),
	CharterSchool			varchar(200),
	MathMeanScaleScore		integer,
	MathFallsFarBelowPer	integer,
	MathApproachesPer		integer,
	MathMeetsPer			integer,
	MathExceedsPer			integer,
	MathPassingPer			integer,
	ReaMeanScaleScore		integer,
	ReaFallsFarBelowPer		integer,
	ReaApproachesPer		integer,
	ReaMeetsPer				integer,
	ReaExceedsPer			integer,
	ReaPassingPer			integer,
	WriMeanScaleScore		integer,
	WriFallsFarBelowPer		integer,
	WriApproachesPer		integer,
	WriMeetsPer				integer,
	WriExceedsPer			integer,
	WriPassingPer			integer,
	SciMeanScaleScorePer	integer,
	SciFallsFarBelowPer		integer,
	SciApproachesPer		integer,
	SciMeetsPer				integer,
	SciExceedsPer			integer,
	SciPassingintegerPer 	integer,
    primary key (SchoolEntityID)
);
create table SantaCruz (
	FiscalYear				integer,
	St						varchar(200),
	County					varchar(200),
	LEAEntityID         	integer,
	LEACTDSNumber			integer,
	LEAName					varchar(200),
	SchoolEntityID    		integer,
	SchoolCTDSNumber		integer,
	SchoolName				varchar(200),
	CharterSchool			varchar(200),
	MathMeanScaleScore		integer,
	MathFallsFarBelowPer	integer,
	MathApproachesPer		integer,
	MathMeetsPer			integer,
	MathExceedsPer			integer,
	MathPassingPer			integer,
	ReaMeanScaleScore		integer,
	ReaFallsFarBelowPer		integer,
	ReaApproachesPer		integer,
	ReaMeetsPer				integer,
	ReaExceedsPer			integer,
	ReaPassingPer			integer,
	WriMeanScaleScore		integer,
	WriFallsFarBelowPer		integer,
	WriApproachesPer		integer,
	WriMeetsPer				integer,
	WriExceedsPer			integer,
	WriPassingPer			integer,
	SciMeanScaleScorePer	integer,
	SciFallsFarBelowPer		integer,
	SciApproachesPer		integer,
	SciMeetsPer				integer,
	SciExceedsPer			integer,
	SciPassingintegerPer 	integer,
    primary key (SchoolEntityID)
);

